# Generated by Django 4.2 on 2023-04-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="body",
            field=models.CharField(max_length=300),
        ),
    ]
